#####################################################################
## Package Descriptor
#####################################################################
## version: 1.0
#####################################################################

name: sutils
description: Smart Utilities
version: 0.1.0
type: py-lib
url: https://github.com/ultralightweight/sutils
scm-url: git@github.com:ultralightweight/sutils.git
author: DANA
author-email: mondomhogynincsen@gmail.com

